name: app-tester
on:
  workflow_dispatch:
  schedule:
    - cron: 00 19 * * *

permissions:
  pull-requests: write
  contents: write

jobs:
  test-app:
    name: Get component details
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: pipeline-read

    steps:
      - name: checking out 1st repo
        uses: actions/checkout@v4
        with:
          path: docs
          fetch-depth: 1

      - name: echo git repo-1
        run: |
          echo ${{ github.repository }} 
          echo ${{ github.repository_owner }}

      - name: Get token
        id: token
        run: |
          githubAppID="${{ env.APP_ID }}"
          githubAppPrivateKey="${{ env.APP_PRIVATE_KEY }}"
          echo "Test"
          echo $githubAppID $githubAppPrivateKey
