name: app-tester
on:
  workflow_dispatch:
  schedule:
    - cron: 00 19 * * *

permissions:
  pull-requests: write
  contents: write

jobs:
  test-app:
    name: Get component details
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: pipeline-read

    steps:
      - name: checking out 1st repo
        uses: actions/checkout@v4
        with:
          path: docs
          fetch-depth: 1

      - name: echo git repo-1
        run: |
          echo ${{ github.repository }} 
          echo ${{ github.repository_owner }}

      - name: Get token
        id: token
        run: |
          githubAppID="${{ vars.APP_ID }}"
          githubAppPrivateKey="${{ secrets.APP_PRIVATE_KEY }}" 
          githubAppInstallationId="${{ vars.APP_INSTALL_ID }}"
          githubApiUrl="${{ vars.GH_SERVER_API_URL }}"
          echo "Flag 1"

          iat=$(date +%s)
          # Expire 9 minutes in the future. 10 minutes is the max for GitHub
          exp=$((iat + 540))
          # Generate encoded JWT header
          jwtHeaderRaw='{"alg":"RS256"}'
          jwtHeader=$( echo -n "${jwtHeaderRaw}" | openssl base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n' )
          echo "Flag 2"

          # Generate encoded JWT payload
          jwtPayloadRaw='{"iat":'"${iat}"',"exp":'"${exp}"',"iss":'"${githubAppID}"'}'
          jwtPayload=$( echo -n "${jwtPayloadRaw}" | openssl base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n' )
          # Generate encoded JWT signature
          echo "Flag 3"
          echo -n "${githubAppPrivateKey}" > /tmp/private_key.pem
          jwtSignature=$( openssl dgst -sha256 -sign /tmp/private_key.pem <(echo -n "${jwtHeader}.${jwtPayload}") | openssl base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n' )
          rm /tmp/private_key.pem
          echo "Flag 4"

          jwtToken=${jwtHeader}.${jwtPayload}.${jwtSignature}
          
          echo "Flag "
          
          
          echo "JWT Header: $jwtHeader"
          echo "JWT Payload: $jwtPayload"
          echo "JWT SIGN: $jwtSignature"
          echo "JWT Token: $jwtToken" 
          
          token=$(curl --fail --silent -X POST -H "Authorization: Bearer ${jwtToken}" -H "Accept: application/vnd.github.v3+json" "${githubApiUrl}/app/installations/${githubAppInstallationId}/access_tokens" | jq -r .token)
          
          echo "Access Token: $token"
          echo "jwt=${jwtToken}" >> "${GITHUB_OUTPUT}"
          echo "token=${token}" >> "${GITHUB_OUTPUT}"

      - name: Checkout build pipeline repo
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.REPOSITORY }}
          fetch-depth: 1
          ref: ${{ vars.BRANCH }}
          token: ${{ steps.token.outputs.token }}
          github-server-url: ${{ vars.GH_SERVER_URL }}
          path: pipeline
