name: app-tester
on:
  workflow_dispatch:
  schedule:
    - cron: 00 19 * * *

permissions:
  pull-requests: write
  contents: write

jobs:
  test-app:
    name: Get component details
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: pipeline-read

    steps:
      - name: checking out 1st repo
        uses: actions/checkout@v4
        with:
          path: docs
          fetch-depth: 1

      - name: echo git repo-1
        run: |
          echo ${{ github.repository }} 
          echo ${{ github.repository_owner }}

      - name: Get token
        id: token
        run: |
          githubAppID="${{ vars.APP_ID }}"
          githubAppPrivateKey="${{ secrets.APP_PRIVATE_KEY }}"
          echo "Test"
          echo $githubAppID $githubAppPrivateKey

      - name: GitHub app JWT
        id: github-app-jwt-generator
        uses: jamestrousdale/github-app-jwt-token@0.1.4
        with:
          app-id: $githubAppID
          private-key: $githubAppPrivateKey

      - name: Generate installation access token
        run: |
          $githubApiUrl = https://github.softwareag.com
          GITHUB_APP_JWT=${{ steps.github-app-jwt-generator.outputs.jwt }}
          echo $GITHUB_APP_JWT

