name: app-tester
on:
  workflow_dispatch:
  schedule:
    - cron: 00 19 * * *

permissions:
  pull-requests: write
  contents: write

jobs:
  get-test-file-job:
    name: Get component details from helm charts
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-file.output.matrix }}
    steps:
      - name: create random test file
        id: get-file
        run: |
          touch component_details.json
          echo "{'test-file':'test1'}" > component_details.json
          echo "matrix=$(cat component_details.json | jq -c .)" >> $GITHUB_OUTPUT
          echo "matrix=$(cat component_details.json | jq -c .)"

      - name: test component output
        run: |
          echo "test 1"
          echo ${{ steps.get-file.output.matrix }}
          echo "test 2"
          echo "${{ steps.get-file.output.matrix }}"
          echo "test 3"
          echo ${{ steps.get-file.output }}  
  


  test-component-output:
    name: Test component details from previous jobs-1
    runs-on: ubuntu-latest
    needs: get-test-file-job
    steps:
      - name: test-1
        run: |
          echo "test 1"
           echo ${{ needs.get-component-details.output.matrix }}
           echo "test 2"
           echo "${{ needs.get-component-details.output.matrix }}"
           echo "test 3"
           echo ${{ needs.get-component-details.output }}
           echo "test 4: ${{ toJSON(needs.get-component-details.outputs) }}"

  test-component-output-2:
    name: Test component details from previous jobs-1
    runs-on: ubuntu-latest
    needs: [get-test-file-job]
    steps:
      - name: test-1
        run: |
          echo "test 1"
           echo ${{ needs.get-component-details.output.matrix }}
           echo "test 2"
           echo "${{ needs.get-component-details.output.matrix }}"
           echo "test 3"
           echo ${{ needs.get-component-details.output }}
           echo "test 4: ${{ toJSON(needs.get-component-details.outputs) }}"
