name: output-tester
on:
  workflow_dispatch:
  schedule:
    - cron: 00 19 * * *

  workflow_call:
    inputs:
      date:
        description: 'The date this component was deployed to the environment.'
        required: true
        type: string
      version:
        description: 'Version of the component that has been deployed to the environment.'
        required: true
        type: string
      component:
        description: 'The name of the component that has been deployed to the environment.'
        required: true
        type: string

permissions:
  pull-requests: write
  contents: write

jobs:
  output-recieved-data:
    name: Get component details from helm charts
    runs-on: ubuntu-latest
    steps:
      - name: output recieved data
        run: |
          echo "component: ${{ inputs.component }}"
          echo "date: ${{ inputs.date }}"
          echo "version: ${{ inputs.version }}"
  

